# Generated by Django 3.1.4 on 2021-01-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210102_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='parant',
            new_name='parent',
        ),
    ]
