# Generated by Django 3.0.8 on 2021-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210103_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='kdtek\\images\\kdtek.png', upload_to='kdtek/images'),
        ),
    ]
